# for authentication.js



##

POST http://localhost:9000/users
Content-Type: application/json

{
    "name": "Jim",
    "password": "password"
}

###
POST http://localhost:9000/users
Content-Type: application/json

{
    "name": "Jeff",
    "password": "password"
}
###

GET http://localhost:8080/users

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "name": "Jeff",
    "password": "assword"
}
###
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "name": "Jeff",
    "password": "password"
}